### ISSUE TITLE
Can I save only projected Sparse point in camera coordinates in .png format ?

### ISSUE THREAD

**Issue by Laihu08** [azureology/kitti-velo2cam#1]
Hi, It would be very helpful if you provide me a code to save only projected sparse points in camera coordinates in .png format ? Thanks in advance.

**Comment by azureology** [comment]
First, you can get camera coordinates (u,v) from here:
https://github.com/azureology/kitti-velo2cam/blob/d1af90324f1b09432a8b3a787c7b748c06a79457/proj_velo2cam.py#L46
If i understood correctly, you need a png that only contains projection. 
https://github.com/azureology/kitti-velo2cam/blob/d1af90324f1b09432a8b3a787c7b748c06a79457/proj_velo2cam.py#L38
Comment out this line should do the trick.
