### ISSUE TITLE
为什么kitti雷达投影后的高度这么低

### ISSUE THREAD

**Issue by xuwuzhou** [azureology/kitti-velo2cam#2]
楼主你好，我自己也简单的实现了下点云投影到图像平面，发现投影后的点云高度很低，这合理吗
![2021-07-21 09-50-26 的屏幕截图](https://user-images.githubusercontent.com/44218507/126420230-2223806f-8b68-4f7b-8dc2-4fa8283e625e.png)

**Comment by azureology** [comment]
合理，KITTI点云剪裁过，仔细看纵向不足64线。
