### ISSUE TITLE
深度信息的获取为什么是根据Z轴

### ISSUE THREAD

**Issue by FeiMa-REC** [azureology/kitti-velo2cam#9]
非常感谢作者的开源分享，但是我有一个问题。

KITTI 的雷达坐标系中图像前方点云的深度信息应该是X方向，为什么代码最后使用Z方向作为深度信息显示？

```
velo = np.insert(points,3,1,axis=1).T
velo = np.delete(velo,np.where(velo[0,:]<0),axis=1)
cam = P2.dot(R0_rect.dot(Tr_velo_to_cam.dot(velo)))
cam = np.delete(cam,np.where(cam[2,:]<0),axis=1)
```

这里cam的维度是（3， 60828），也就是前三行维度应该是 --> (x, y, z)

经过一系列的filter处理后得到

```
u,v,z = cam
plt.scatter([u],[v],c=[z],cmap='rainbow_r',alpha=0.5,s=2)
```

为什么最后是根据Z方向的点云深度作为显示呢？Z方向不应该是图像正上方的点云深度吗？

非常希望得到您的答疑！

**Comment by azureology** [comment]
注意看，代码里的uv**z**是相机坐标（下图红色）而不是点云。
The z you mention here in [u, v, z] means depth in camera(red one below), not in lidar coord.
![image](https://github.com/azureology/kitti-velo2cam/assets/34760051/21d05e09-25ba-455d-955c-53a6587ae610)

**Comment by FeiMa-REC** [comment]
明白了！非常感谢您的答复！
